[2023-01-10T20:53:13.401-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: walmart-ml-workflow.train scheduled__2023-01-10T00:00:00+00:00 [queued]>
[2023-01-10T20:53:13.412-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: walmart-ml-workflow.train scheduled__2023-01-10T00:00:00+00:00 [queued]>
[2023-01-10T20:53:13.412-0500] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-10T20:53:13.412-0500] {taskinstance.py:1284} INFO - Starting attempt 3 of 4
[2023-01-10T20:53:13.412-0500] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-10T20:53:13.421-0500] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): train> on 2023-01-10 00:00:00+00:00
[2023-01-10T20:53:13.423-0500] {standard_task_runner.py:55} INFO - Started process 4485 to run task
[2023-01-10T20:53:13.429-0500] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'walmart-ml-workflow', 'train', 'scheduled__2023-01-10T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/walmart-ml-workflow.py', '--cfg-path', '/var/folders/lc/0q_5vmf5385c78mr7v2ntch00000gn/T/tmpczsw22f7']
[2023-01-10T20:53:13.432-0500] {standard_task_runner.py:83} INFO - Job 23: Subtask train
[2023-01-10T20:53:13.603-0500] {task_command.py:389} INFO - Running <TaskInstance: walmart-ml-workflow.train scheduled__2023-01-10T00:00:00+00:00 [running]> on host toyosis-macbook-pro.local
[2023-01-10T20:53:13.644-0500] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=toyosibamidele@gmail.com
AIRFLOW_CTX_DAG_OWNER=Toyosi Bami
AIRFLOW_CTX_DAG_ID=walmart-ml-workflow
AIRFLOW_CTX_TASK_ID=train
AIRFLOW_CTX_EXECUTION_DATE=2023-01-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-10T00:00:00+00:00
[2023-01-10T20:53:13.646-0500] {subprocess.py:63} INFO - Tmp dir root location: 
 /var/folders/lc/0q_5vmf5385c78mr7v2ntch00000gn/T
[2023-01-10T20:53:13.647-0500] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 ~/airflow/scripts/train.py']
[2023-01-10T20:53:13.653-0500] {subprocess.py:86} INFO - Output:
[2023-01-10T20:53:14.765-0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-01-10T20:53:14.767-0500] {subprocess.py:93} INFO -   File "/Users/toyosibamidele/airflow/scripts/train.py", line 19, in <module>
[2023-01-10T20:53:14.767-0500] {subprocess.py:93} INFO -     df = pd.read_csv(path.joinpath('dat/train-store1.csv'))
[2023-01-10T20:53:14.768-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
[2023-01-10T20:53:14.769-0500] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-01-10T20:53:14.769-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
[2023-01-10T20:53:14.770-0500] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-01-10T20:53:14.771-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
[2023-01-10T20:53:14.771-0500] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2023-01-10T20:53:14.772-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
[2023-01-10T20:53:14.773-0500] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2023-01-10T20:53:14.773-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
[2023-01-10T20:53:14.774-0500] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2023-01-10T20:53:14.774-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
[2023-01-10T20:53:14.775-0500] {subprocess.py:93} INFO -     self.handles = get_handle(
[2023-01-10T20:53:14.775-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
[2023-01-10T20:53:14.776-0500] {subprocess.py:93} INFO -     handle = open(
[2023-01-10T20:53:14.777-0500] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/Users/toyosibamidele/airflow/dat/train-store1.csv'
[2023-01-10T20:53:14.875-0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-01-10T20:53:14.886-0500] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-01-10T20:53:14.892-0500] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=walmart-ml-workflow, task_id=train, execution_date=20230110T000000, start_date=20230111T015313, end_date=20230111T015314
[2023-01-10T20:53:14.904-0500] {standard_task_runner.py:100} ERROR - Failed to execute job 23 for task train (Bash command failed. The command returned a non-zero exit code 1.; 4485)
[2023-01-10T20:53:14.921-0500] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-10T20:53:14.938-0500] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
